Allow changing log-levels for add-ons
openhab/openhab-webui pull request #1452
Opened 2022-07-17 11:39 UTC by J-N-K

Closes #1351 

Signed-off-by: Jan N. Klug <github@klug.nrw>

2022-07-17 11:44 UTC, J-N-K commented
<img width="1218" alt="Bildschirmfoto 2022-07-17 um 13 43 52" src="https://user-images.githubusercontent.com/5159123/179396578-43a5137d-7bae-45d6-b0ba-f178d75c4f60.png">

2022-07-24 10:44 UTC, ghys commented
Tried it and I don't see the configuration for the Kodi binding anymore:

![image](https://user-images.githubusercontent.com/2004147/180643313-50dc0fb6-da79-40a4-b001-8d0c897223fa.png)

![image](https://user-images.githubusercontent.com/2004147/180643319-42f0e3d4-946b-4e43-9a08-b77c3817784b.png)

The reason is that the configDescriptionURI is empty (3.3.0 Release) in `/rest/addons/binding-kodi`:

![image](https://user-images.githubusercontent.com/2004147/180643370-ebdb94e7-d66a-40a5-bb44-b817ad27acfe.png)

Since it appears to work in your screenshot above, I would suspect that the configDescriptionURI _can_ eventually appear in the `/rest/addons` response, but in this case it does not? Otherwise it might be safer to still try to retrieve it from `/rest/bindings` if is identified as a binding, like before.

2022-07-24 10:53 UTC, J-N-K commented
Did you try with a snapshot after https://github.com/openhab/openhab-core/pull/3045 was merged?

```
{
  "id": "binding-kodi",
  "label": "Kodi Binding",
  "version": "3.4.0.SNAPSHOT",
  "compatible": true,
  "contentType": "application/vnd.openhab.feature;type=karaf",
  "link": "https://www.openhab.org/addons/bindings/kodi/",
  "author": "openHAB",
  "verifiedAuthor": true,
  "installed": true,
  "type": "binding",
  "configDescriptionURI": "binding:kodi",
  "keywords": "",
  "countries": "",
  "connection": "",
  "properties": {},
  "loggerPackages": [
    "org.openhab.binding.kodi"
  ]
}
```

2022-07-24 11:17 UTC, ghys commented
Ah, my bad, I thought the 3.3.0 core was sufficient, I missed you mentioned the dependency to https://github.com/openhab/openhab-core/pull/3045. Will do.

2022-07-24 11:29 UTC, ghys commented
Also in the `/settings/things/add` page where you select the binding:

![image](https://user-images.githubusercontent.com/2004147/180644768-9db2a387-6f55-4ff6-89be-ea83b24c46e7.png)

The gear icon link to configure the binding (if it has a configDescription) needs to be updated to the new route.
It's important because it's AFAIK still the only way to configure a binding that wasn't added from the distribution.
Also it could make sense to display this icon regardless of whether a configuration exists now since the screen also includes the log level section.

2022-07-24 19:38 UTC, J-N-K commented
Currently the "old route" will still work. This will change with [openhab-core#3050](https://github.com/openhab/openhab-core/pull/3050/files) but that's more at the beginning of next year. There I'm also working on reporting manually installed add-ons (i.e. in addons folder) in the REST API, to we can drop the configuration at that place.

2022-07-29 19:51 UTC, ghys commented
Yes the route works but it fails to find the add-on it should pull the config from:

When clicking that gear icon besides the Hue entry it navigates to `/settings/addons/hue/config` which fails to render:

![image](https://user-images.githubusercontent.com/2004147/181832125-d228c74a-5aad-4e58-a8c8-e2ca6574af67.png)

This is due to a `GET /rest/addons/hue` which results in a 404 error (the former call was `/rest/bindings/hue`).
Now it could be tricky to translate the bindingId (`hue`) we get from the binding list page into an add-on id. It could be `binding-hue` or `marketplace:{something}` or yet something else entirely depending on the underlying add-on service.
I have no good solution for this, and I can only offer to keep the old `binding-config.vue` along with a separate route in `routes.js` for this page. It will not feature the log level sections of the new add-on configuration page, but these can still be accessed from the add-on store.

2022-08-04 17:40 UTC, ghys requested changes
Alright, great. Quite unfortunate to have to have 2 separate pages to configure the bindings, but it's only a little overhead and it solves other problems until all add-ons can be configured, so "oh well".

Last cosmetic suggestions below on the section titles in the add-on config page to make them look better. They are also bigger because there might be config description groups in the configuration, which would render group titles on the same level.

![image](https://user-images.githubusercontent.com/2004147/182915187-c9ad2306-380d-4643-a38e-c3ecc252b9ab.png)

![image](https://user-images.githubusercontent.com/2004147/182915115-7414b054-3c97-47c0-9699-ff99e48fc98f.png)

2022-08-04 17:40 UTC, ghys commented on bundles/org.openhab.ui/web/src/pages/settings/addons/addon-config.vue
> +        <f7-list class="col wide">
```suggestion
      <f7-col>
        <f7-block-title medium>Add-on log settings</f7-block-title>
        <f7-list class="col wide">
```

2022-08-04 17:40 UTC, ghys commented on bundles/org.openhab.ui/web/src/pages/settings/addons/addon-config.vue
> +        <config-sheet
```suggestion
      <f7-col>
        <f7-block-title medium>Add-on configuration</f7-block-title>
        <config-sheet
```

2022-08-09 17:52 UTC, ghys approved these changes
OK, LGTM!
Since it's still technically a draft, please mark it ready when you are.

2022-08-09 18:13 UTC, J-N-K commented
I would prefer to keep user-facing changes for beginning of next year (i.e. after release), otherwise we'll have the same discussion as in https://github.com/orgs/openhab/teams/architecture-council/discussions/15 again: Not enough visible changes to justify a change in Java version.

2023-01-03 14:02 UTC, ghys requested changes

2023-01-03 14:02 UTC, ghys commented on bundles/org.openhab.ui/web/src/pages/settings/addons/addon-details.vue
> +      console.error('configUri' + this.addon.configDescriptionURI)
I had another check: can you remove this debugging leftover?

2023-01-16 23:42 UTC, ghys approved these changes

2023-01-16 23:53 UTC, ghys commented
This now needs rebasing and fixing the conflicts since #1468 was merged.

2023-01-17 18:35 UTC, J-N-K commented
Done. However, to work a regression core needs to be fixed: https://github.com/openhab/openhab-core/pull/3322

2023-01-21 21:54 UTC, hmerk commented
As https://github.com/openhab/openhab-core/pull/3322 was merged 3 days ago, could this one be merged as well ?
Would love to try this feature with one of the next SNAPSHOTs ....

2023-01-22 07:21 UTC, merged

2023-01-22 09:34 UTC, hmerk commented
@ghys Thanks Yannick !

2023-01-22 11:40 UTC, hmerk commented
@J-N-K Great job, working as expected 👍