[blockly] add new list, item, persistence, text blocks
openhab/openhab-webui pull request #1549
Opened 2022-11-21 22:06 UTC by stefan-hoehn

Signed-off-by: Stefan Höhn <stefan@andreaundstefanhoehn.de>

oh_text_replace: a new text replace block that is missing in the standard text block section
oh_list_concatenate: allows to concatenate two lists into a new lists
oh_taggeditems: retrieve a list of items identified by one or multiple tags
oh_get_persistvalue: add new previousState (new mutating block)
oh_transformation: fix help url

2022-11-27 16:50 UTC, stefan-hoehn commented
@ghys Do you mind having a quick look at it, so we can deliver it with the current milestone

2022-12-02 22:01 UTC, stefan-hoehn commented
@lolodomo would you be able to review it, so there is a chance that it still can make it into main before the feature freeze?

2022-12-02 22:16 UTC, ghys commented
I'm still around... I'll review it and other pending PRs this week-end.

2022-12-02 22:20 UTC, stefan-hoehn commented
> I'm still around... I'll review it and other pending PRs this week-end.

Yannick, I know, I appreciate it. please take care of yourself.! 🤗

2022-12-04 13:10 UTC, stefan-hoehn commented
FYI I took the chance and added a few changes lately and a fix all of which are documented above. The reason is that by using the blocks myself I discovered some short comings, so I improved them.

The PR is now stable again and ready to be reviewed.

2022-12-04 22:51 UTC, ghys requested changes
You're getting good at this, I have just this to moan about but otherwise it's all good.

2022-12-04 22:51 UTC, ghys commented on bundles/org.openhab.ui/web/src/assets/definitions/blockly/utils.js
> +      `    case regex_time_sec.test(datetime): return ${zdt}.parse(today+datetime+'+00:00', dtf.ofPattern('yyyy-MM-dd HH:mm:ssz'));`,
```suggestion
      `    case regex_time_min.test(datetime): return ${zdt}.parse(today + datetime+':00+00:00', dtf.ofPattern('yyyy-MM-dd HH:mm:ssz'));`,
      `    case regex_time_sec.test(datetime): return ${zdt}.parse(today + datetime+'+00:00', dtf.ofPattern('yyyy-MM-dd HH:mm:ssz'));`,
```

2022-12-07 21:55 UTC, stefan-hoehn commented
@ghys Your change has been applied.

2022-12-10 10:22 UTC, ghys approved these changes
There was still missing spaces that I didn't fix in the earlier suggestion, I did it myself.

LGTM thanks.

2022-12-10 10:40 UTC, merged