add rulesWithTags to oh-repeater
openhab/openhab-webui pull request #1724
Opened 2023-02-19 12:34 UTC by stefan-hoehn

fixes #1721 Add Scenes option to oh-repeater component

This PR adds the possibility to iterate over a list of rules queried via a tag.

For example it allows to create a list of Scenes via the oh-repeater by using the rulesTag = Scene and trigger the rule via a oh-button.

Example

```
slots:
  default:
    - component: oh-list
      slots:
        default:
          - component: oh-repeater
            config:
              for: scene
              sourceType: rulesWithTags
              ruleTags: Scene
            slots:
              default:
                - component: oh-button
                  config:
                    action: rule
                    actionRule: =loop.scene.uid
                    text: =loop.scene.name
```

2023-02-19 22:52 UTC, florian-h05 requested changes
In general LGTM, please have a look at my comments.

We should also keep in mind that this approach works fine if you are logged in as an admin user, but if you are logged out or only logged in as a regular user, this won't work because the `/rest/rules` endpoint requires admin role.
We therefore need some way to access the scenes as unauthorized user, just as we can access the Items. This should be reported and discussed in openHAB core, because we need unauthorized access to scene rules.

I'd expect that we then have to adjust the REST endpoint, so I'd probably wait with merging this. IMO there is no value yet for the most users because they normally shouldn't be logged in as admin.

2023-02-19 22:52 UTC, florian-h05 commented on bundles/org.openhab.ui/web/src/assets/definitions/widgets/system/repeater.js
> +  pt('ruleTags', 'Rule Tags', 'Iterate over rules with the given tags (comma-separated, for "rulesWithTags" source type)'),
You need to add the `rulesWithTags` source type to the options array above in line 12.
Remember to regenerate the component docs after this.

2023-02-19 22:52 UTC, florian-h05 commented on bundles/org.openhab.ui/web/src/components/widgets/standard/list/default-list-item.js
> -
Can you please revert this change?

2023-02-19 22:52 UTC, florian-h05 commented on bundles/org.openhab.ui/web/src/components/widgets/system/oh-repeater.vue
> +        return this.$oh.api.get('/rest/rules?summary=true' + '&tags=' + this.config.ruleTags).then((r) => r.sort(compareRules))
```suggestion
        return this.$oh.api.get('/rest/rules?summary=true' + '&tags=' + this.config.ruleTags).then((r) => Promise.resolve(r.sort(compareRules)))
```

This asyncComputed property returns a promise for all cases, so it should behave the same here.

2023-02-20 08:56 UTC, hmerk commented
> This should be reported and discussed in openHAB core, because we need unauthorized access to scene rules.

Issue opened 
https://github.com/openhab/openhab-core/issues/3390

2023-02-20 09:47 UTC, florian-h05 submitted a review, later dismissed
One minor comment, and please fix the linting `npm run lint:fix`.
If this is done, we are ready to merge this.

2023-02-20 09:47 UTC, florian-h05 commented on bundles/org.openhab.ui/web/src/components/widgets/system/oh-repeater.vue
> +        return this.$oh.api.get('/rest/rules?summary=true' + '&tags=' + this.config.ruleTags).then((r) => Promise.resolve(r.sort(compareRules)))
```suggestion
        return this.$oh.api.get('/rest/rules?summary=true&tags=' + this.config.ruleTags).then((r) => Promise.resolve(r.sort(compareRules)))
```

2023-02-20 21:18 UTC, hmerk commented
Core PR created by @J-N-K 
https://github.com/openhab/openhab-core/pull/3392

2023-02-20 22:24 UTC, stefan-hoehn commented on bundles/org.openhab.ui/web/src/components/widgets/system/oh-repeater.vue
> +        return this.$oh.api.get('/rest/rules?summary=true' + '&tags=' + this.config.ruleTags).then((r) => Promise.resolve(r.sort(compareRules)))
🤦 done

2023-02-21 18:18 UTC, ghys approved these changes

2023-02-21 18:19 UTC, ghys commented
Let's wait for https://github.com/openhab/openhab-core/pull/3392 before merging.

2023-02-21 18:33 UTC, hmerk commented
> Let's wait for [openhab/openhab-core#3392](https://github.com/openhab/openhab-core/pull/3392) before merging.

It was merged just now 😉

2023-02-21 18:58 UTC, merged

2023-02-21 19:08 UTC, hmerk commented
@stefan-hoehn @ghys @florian-h05 @J-N-K @kaikreuzer
Thanks to all of you for this joint effort.
I think that having the scene editor and the option to use it with the oh-repeater is a great new feature for openHAB 4 👍