[BasicUI] Add the "follow system" theme
openhab/openhab-webui pull request #1829
Opened 2023-04-08 18:44 UTC by lolodomo

Closes #1828

3 themes are now available! bright, dark and system.
Theme previously named "default" has been renamed into "bright".
"default" is still accepted for backward compatibility.

Tested with Fiorefox, Chrome and Edge on Windows 10.
Tested with Chrome on Android.

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

2023-04-09 07:35 UTC, dilyanpalauzov commented
> I tried now the explicit Dark mode. I have to say that for SetPoint items the UP and DOWN arrow are black on dark-grey background and therefore hard to perceive in openHAB 3.4/Basic UI. For Switch item=r3_manual mappings=[ON="Ръчно", OFF="Автоматично"] when the current value is OFF the text “Ръчно” is presented in black on dark--gray background. This has very low contrast and is therefore suboptimal.

Is this also addressed here?

2023-04-09 07:44 UTC, lolodomo commented
No, as mentioned in the PR title, this PR adds the new "follow system" theme, meaning an automatic choice between bright and dark themes depending on the system current mode.
This PR makes no change on colors used by the bright and dark themes.

2023-04-09 08:35 UTC, dilyanpalauzov commented
Regarding the low contrast for Basic UI in dark mode I filled https://github.com/openhab/openhab-webui/issues/1831 .

My understanding of the web interfaces in openHAB 3.4 so far is:
* For MainUI any unauthenticated user can visit `/about` and setup the “Mode preferences”: Auto (System preference), Light, Dark; and the “Enable Web Audio sink support”.  These settings are per device (per browser, actually)
* The above settings are however irrelevant for BasicUI.  To adjust the latter one has to visit `/settings/services/org.openhab.basicui`.  Then the settings are not per device, but for all BasicUI instances, whereever they are loaded.  Moreover to alter that settings the user has to authenticate towards openHAB.

For me these two-fold settings are contradicting each other.  May I suggest to remove from the URL `/settings/services/org.openhab.basicui` the settings, which are duplicated from `/about` (like color mode and Web Audio sink preferences). Then use on the device where BasicUI is loaded the preferences set at `/about`?  This will simplify things.

2023-04-09 08:53 UTC, lolodomo commented
Please create a separate feature request and avoid polluate this PR. I will then comment.

2023-04-12 08:10 UTC, lolodomo commented
I have to update this PR now that PR #1834 has been merged.

2023-04-12 08:17 UTC, lolodomo commented
PR is again ready for review.

2023-04-12 20:10 UTC, kaikreuzer requested changes
Thanks - just a very minor change request.

2023-04-12 20:10 UTC, kaikreuzer commented on bundles/org.openhab.ui.basic/src/main/resources/OH-INF/config/config.xml
> +				<option value="system">Follow system</option>
```suggestion
				<option value="system">Follow System</option>
```

2023-04-12 20:10 UTC, kaikreuzer commented on bundles/org.openhab.ui.basic/src/main/resources/OH-INF/i18n/basic.properties
> +ui.config.basic.theme.option.system = Follow system
```suggestion
ui.config.basic.theme.option.system = Follow System
```

2023-04-13 08:10 UTC, lolodomo commented on bundles/org.openhab.ui.basic/src/main/resources/OH-INF/i18n/basic.properties
> +ui.config.basic.theme.option.system = Follow system
Done

2023-04-13 20:31 UTC, kaikreuzer approved these changes
Thanks!

2023-04-13 20:31 UTC, merged