Thing and triggerchannel pickers
openhab/openhab-webui pull request #2129
Opened 2023-10-10 12:56 UTC by d51x

discussion #2128

2023-11-17 20:07 UTC, florian-h05 requested changes
Thanks for this PR, however it does not look good on desktops using the desktop theme:

![image](https://github.com/openhab/openhab-webui/assets/73423173/f66c3465-ab88-46ae-b825-4fbb0065f683)

2024-10-26 16:52 UTC, florian-h05 commented
@d51x Still on it?

2024-10-26 17:46 UTC, d51x commented
> @d51x Still on it?

No, another system of a smart house conquered my heart)))

2024-10-26 19:33 UTC, florian-h05 commented
Out of interest: Which one?

2025-04-05 14:21 UTC, florian-h05 commented
Superseded by #3126.

2025-04-05 14:21 UTC, closed without merging