Limit add-on settings menu list to bundles
openhab/openhab-webui pull request #2217
Opened 2023-12-13 15:32 UTC by mherwege

When installing rule templates or UI components or blockly libraries from the marketplace, they get an entry in the add-on settings menu. There is nothing that can be configured in these types of add-ons. Therefore limit the list to bundles and features.

2023-12-13 23:00 UTC, florian-h05 requested changes

2023-12-14 07:25 UTC, mherwege commented on bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
> +        this.addonsInstalled = data.filter(a => { return a.installed && ['application/vnd.openhab.bundle', 'application/vnd.openhab.feature;type=karfile'].includes(a.contentType) })
I thought I scanned the code well enough. I clearly still missed something.

See also this related core PR: https://github.com/openhab/openhab-core/pull/3921

The one thing I couldn't figure out yet is how to make the logger for marketplace installed add-ons visible.

2023-12-14 07:57 UTC, florian-h05 commented on bundles/org.openhab.ui/web/src/pages/settings/menu/settings-menu.vue
> +        this.addonsInstalled = data.filter(a => { return a.installed && ['application/vnd.openhab.bundle', 'application/vnd.openhab.feature;type=karfile'].includes(a.contentType) })
👍 

Yeah, I’ve also noticed that the logger setting is missing for marketplace add-ons, thanks for making it available for JAR add-ons.

2023-12-14 07:57 UTC, florian-h05 approved these changes
LGTM, thanks!

2023-12-14 07:58 UTC, merged