[Blockly] Riemann sum persistence extension and js tern definitions
openhab/openhab-webui pull request #2893
Opened 2024-12-02 10:33 UTC by mherwege

Depends on https://github.com/openhab/openhab-js/pull/401
Depends on https://github.com/openhab/openhab-core/pull/4461

This will also require a new js scripting library release.

2024-12-16 08:25 UTC, mherwege commented
@stefan-hoehn FYI, not to be merged yet, as waiting for the core and javascript enhancements.

2024-12-16 09:15 UTC, stefan-hoehn commented
Can you add what the extension is about. We should avoid overloading blocks with too many things (not saying you do so 😉)

2024-12-16 11:49 UTC, mherwege commented
> Can you add what the extension is about. We should avoid overloading blocks with too many things (not saying you do so 😉)

I have added some description in the first post. This is about keeping the persistence blocks in line with the (still proposed) core and js scripting extensions.
Agreed it should not be overloaded. But I believe this is an important part of rules, and being able to use all variations of persistence extensions in Blocky feels important to me.

2025-02-20 21:30 UTC, stefan-hoehn commented
And let's not forget to update the blockly docs after that ;-)

2025-04-05 13:17 UTC, florian-h05 requested changes
Overall LGTM, thanks! Please take a look at my comments.

@stefan-hoehn Can you please take a look at the Blockly changes?

2025-04-05 13:17 UTC, florian-h05 commented on bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-persistence.js
> +    riemannType = (riemannType === 'undefined') ? '' : `, ${itemCode}.persistence.${riemannType}`
Let's use static access to the RiemannType:

```suggestion
    riemannType = (riemannType === 'undefined') ? '' : `, items.${riemannType}`
```

2025-04-05 13:17 UTC, florian-h05 commented on bundles/org.openhab.ui/web/src/assets/openhab-js-tern-defs.json
It would be great if you could define the RiemannType in the tern defs and that it is static accesible on the `items` namespace, but TBH I am not sure if that's really possible as JS does not know enums.
What might be a trick to get it working though is to define RiemannType as object with the enum values as string properties.

2025-04-05 19:57 UTC, mherwege commented on bundles/org.openhab.ui/web/src/assets/openhab-js-tern-defs.json
I think I understand what you mean, but I honestly don't know much about tern definitions in the first place. My change is just by analogy. So I am unsure on how to atack this.

2025-04-05 19:58 UTC, mherwege commented on bundles/org.openhab.ui/web/src/assets/definitions/blockly/blocks-persistence.js
> +    riemannType = (riemannType === 'undefined') ? '' : `, ${itemCode}.persistence.${riemannType}`
done

2025-04-05 21:25 UTC, florian-h05 commented on bundles/org.openhab.ui/web/src/assets/openhab-js-tern-defs.json
I have just pushed a commit addressing this :+1:

2025-04-05 21:25 UTC, florian-h05 approved these changes
LGTM, thanks!

Waiting for @stefan-hoehn to take a look at the Blockly code.

2025-04-06 06:06 UTC, mherwege commented on bundles/org.openhab.ui/web/src/assets/openhab-js-tern-defs.json
Thanks

2025-04-07 15:56 UTC, stefan-hoehn commented
The following block

<img width="990" alt="image" src="https://github.com/user-attachments/assets/f2c7b8ed-84fb-459c-88e0-ba11e6eb7543" />

generates

> console.info(('rieman sum garden temp' + String(items.getItem('garten_temperature').persistence.riemannSumSince(time.ZonedDateTime.now().minusHours(1), items.RiemannType.LEFT)?.numericState)));

Unfortunately, I can't test the functionality as I currently have no 5.x backend yet.

2025-04-07 15:59 UTC, stefan-hoehn approved these changes

2025-04-07 16:02 UTC, stefan-hoehn commented
Sorry, I only noticed now that you already did it 🙏🏻
https://github.com/openhab/openhab-docs/pull/2477

2025-04-07 17:20 UTC, merged

2025-04-07 17:20 UTC, mherwege commented
> but I think the blockly docs update is still missing?

@stefan-hoehn I did update it in the same PR you already merged. But must admit I did not redo the images. And it largely links to the broader documentation for more info. Let me know if this is enough.

2025-04-07 17:32 UTC, stefan-hoehn commented
Sure, let's leave the images like that. As long as you have mentioned the entries of the drop down and the new field that comes up when choosing the Riemann properties then that's fine.